### ISSUE TITLE
[Workaround available] Unable to turn quests in

### ISSUE THREAD

**Issue by MichailiK** [Avalon-Entertainment/bkrpg-support#17]
_Reported by 🎼Catwhisperer🐾#8778 (aka. MagicMeowzer)_
"Again it is impossible to turn in the quest for the copper items. I have all requested items (2 copper ingots, 1 worn item) but it doesn't let me turn that quest in, even when it is this time not the problem of having equipped the worn item - it must be other thing"

## Workaround
Dropping the quest and taking it again seems to let it return the items.
## Workaround 2
Using the `sort`-command fixes it as well.

**Comment by MichailiK** [comment]
Addition by Stein#1000: I didn't do the same as Meowzer, it worked for me the first time.

**Comment by avalonrising** [comment]
If a quest drop is at the end of a players inventory, and multiple items are required for the quest. the items will not be useable for turn in."

Can be worked around by doing a!sort

**Comment by avalonrising** [comment]
This should be fixed now, I'll post about it being fixed. If we don't get any more reports about it for a week, we can keep this closed
