### ISSUE TITLE
[Feature Request] Make A! a valid prefix for Alethea.

### ISSUE THREAD

**Issue by MichailiK** [Avalon-Entertainment/bkrpg-support#2]
_Suggested by Kanami#7855 (aka. Jackie) and Michaili#0406_

Making **A!** as a third prefix is convenient for all Mobile users. Since they intend to start sentences in upper-case, making it less complicated and perhaps more enjoyable for Mobile users.

**Comment by avalonrising** [comment]
That's the reason ## was added as a prefix, as it's on all mobile keyboards for discord as far as I know,
But we'll see

**Comment by MichailiK** [comment]
On iOS, the problem with **##** I see is that Discord will think you are about to mention a Text Channel, which will reset the keyboard back to the alphabets, which makes it require more clicks and time than using **a!**. Having **A!** saves a click on the caps-key and makes, to be honest, the game more enjoyable (from my point, it's annoying me to click on the caps key every time I want to use a command).

**Using a!** :
![Primary prefix using iOS keyboard](https://i.imgur.com/ihzRHaX.gif)
**Using ##**:
![Secondary prefix using iOS keyboard](https://i.imgur.com/yZ5YzO9.gif)

**Comment by avalonrising** [comment]
![image](https://user-images.githubusercontent.com/46388944/50719323-31784980-10e6-11e9-837d-54073bd542b8.png)
Try using this # button

**Comment by MichailiK** [comment]
Oh, I forgot that the the #-Button is there! Well, perhaps you could still implement it as a third prefix. Otherwise we could close this Issue.

**Comment by avalonrising** [comment]
A! is now added as a prefix
