### ISSUE TITLE
[Ability Request] Taunt ability for Warriors

### ISSUE THREAD

**Issue by MichailiK** [Avalon-Entertainment/bkrpg-support#3]
_Requested by Kanami#7855 (aka. Jackie)_

Warriors using the Taunt ability will be more likely attacked by all monsters and the player takes +50% damage. The Taunt will last for 1 minute.

**Comment by avalonrising** [comment]
Closing because it's already coming, and I've told Jackie multiple times taunting is coming only after they reach a certain point in the storyline.
