### ISSUE TITLE
XP Leaderboard

### ISSUE THREAD

**Issue by MichailiK** [Avalon-Entertainment/bkrpg-support#8]
Suggested by storyTeller#4519

**Comment by avalonrising** [comment]
"leaderboards for seeing who has the highest stats so we can get a perspective on how far ahead people are"
_- MrMeme#9651_

**Comment by avalonrising** [comment]
This is nice and easy, so going to start on this now

**Comment by avalonrising** [comment]
Added as bk!lb or bk!leaderboard
